services:
  postgres:
    image: postgres:16
    container_name: blog-postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    ports:
      - "5432:5432"
    volumes:
      - blog_pgdata:/var/lib/postgresql/data

volumes:
  blog_pgdata:
