spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: blog
    password: blog

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
